spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: "none"
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  datasource:
    data: classpath:data.sql
    platform: h2
    driverClassName: org.h2.Driver
    url: jdbc:h2:mem:~/prices
    username: assignment
    password: bits123
    initialization-mode: always
conversion-rates:
  usd: 72.45
  euro: 99.91
server:
  port: 8080
review-service:
  url: "http://localhost:8081"
  reviewsByCourseId: "/reviews/courses/"